# Generated by Django 3.1.4 on 2021-06-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoduldetail',
            options={'verbose_name': 'eModul detail', 'verbose_name_plural': 'eModul detail'},
        ),
    ]
