# Generated by Django 3.1.4 on 2021-06-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emodul', '0002_auto_20210616_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='EModulComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Komentar')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emodul.emoduldetail', verbose_name='EModul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'eModul comment',
                'verbose_name_plural': 'eModul comment',
            },
        ),
    ]
