# Generated by Django 3.1.4 on 2021-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0004_auto_20210625_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emodul',
            name='tanggal',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Upload'),
        ),
    ]
