# Generated by Django 3.1.4 on 2021-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0005_auto_20210625_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoduldetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Berkas'),
        ),
    ]
