# Generated by Django 3.1.4 on 2021-06-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0006_auto_20210626_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='emodulbookmark',
            name='tanggal',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Bookmark'),
        ),
    ]
