# Generated by Django 3.1.4 on 2021-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0007_emodulbookmark_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='emodul',
            name='jumlah_modul',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Jumlah Modul'),
        ),
    ]
