# Generated by Django 3.1.7 on 2021-03-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EModul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, verbose_name='Judul modul')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emodul', to='akademik.matakuliah', verbose_name='Mata kuliah')),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emodul', to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'eModul',
                'verbose_name_plural': 'eModul',
            },
        ),
        migrations.CreateModel(
            name='EModulDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, verbose_name='Judul dokumen')),
                ('jumlah_halaman', models.SmallIntegerField(blank=True, null=True, verbose_name='Jumlah halaman')),
                ('file', models.FileField(upload_to=None, verbose_name='Berkas')),
                ('emodul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='emodul.emodul', verbose_name='EModul')),
            ],
            options={
                'verbose_name': 'sModul detail',
                'verbose_name_plural': 'sModul detail',
            },
        ),
        migrations.CreateModel(
            name='EModulBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.PositiveSmallIntegerField(verbose_name='Halaman')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='emodul.emoduldetail', verbose_name='EModul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'eModul bookmark',
                'verbose_name_plural': 'eModul bookmark',
            },
        ),
        migrations.CreateModel(
            name='EModulAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.PositiveSmallIntegerField(verbose_name='Halaman')),
                ('text', models.TextField(verbose_name='Text anotasi')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='emodul.emoduldetail', verbose_name='EModul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'eModul annotation',
                'verbose_name_plural': 'eModul annotation',
            },
        ),
    ]
