# Generated by Django 3.1.4 on 2021-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210320_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='images/foto_profil/default.jpg', null=True, upload_to='images/foto_profil/', verbose_name='Foto'),
        ),
    ]
