# Generated by Django 3.1.4 on 2021-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pria'), (2, 'Wanita')], default=1, verbose_name='Gender'),
        ),
    ]
