# Generated by Django 3.1.7 on 2021-03-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_hp',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+62123456789', help_text='Gunakan format internasional (+628XXXXXX)', max_length=128, region=None, verbose_name='Nomor HP/WA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_user_lengkap',
            field=models.BooleanField(default=False, verbose_name='Profil user lengkap'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mahasiswa'), (2, 'Dosen')], default=1, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='ProfilMahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=5, null=True, verbose_name='Semester')),
                ('kelas', models.CharField(blank=True, max_length=5, null=True, verbose_name='Kelas')),
                ('no_absen', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. Absen')),
                ('profil_mahasiswa_lengkap', models.BooleanField(default=False, verbose_name='Profil mahasiswa lengkap')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.programstudi', verbose_name='Program studi')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil mahasiswa',
                'verbose_name_plural': 'profil mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='ProfilDosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=12, verbose_name='NIDN')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_dosen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil dosen',
                'verbose_name_plural': 'profil dosen',
            },
        ),
    ]
