# Generated by Django 3.1.7 on 2021-03-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama jurusan')),
                ('ketua_jurusan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ketua jurusan')),
            ],
            options={
                'verbose_name': 'jurusan',
                'verbose_name_plural': 'jurusan',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama program studi')),
                ('kode', models.CharField(max_length=50, verbose_name='Kode')),
                ('jenjang', models.CharField(choices=[('D-I', 'D-I'), ('D-II', 'D-II'), ('D-III', 'D-III'), ('D-IV', 'D-IV')], max_length=10, verbose_name='Jenjang')),
                ('psdku', models.BooleanField(verbose_name='Prodi di luar kampus utama')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurusan_prodi', to='akademik.jurusan', verbose_name='Jurusan')),
                ('ketua_prodi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ketua program studi')),
            ],
            options={
                'verbose_name': 'program studi',
                'verbose_name_plural': 'program studi',
            },
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama mata kuliah')),
                ('kode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, verbose_name='Semester')),
                ('sks_teori', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah SKS teori')),
                ('sks_praktik', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah SKS praktik')),
                ('jam_teori', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah jam teori')),
                ('jam_praktik', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah jam praktik')),
                ('program_studi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.programstudi', verbose_name='Program studi')),
            ],
            options={
                'verbose_name': 'mata kuliah',
                'verbose_name_plural': 'mata kuliah',
            },
        ),
    ]
